# Generated by Django 4.2.7 on 2024-05-10 19:54

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/default.jpg",
                upload_to=account.models.user_avatar_path,
            ),
        ),
    ]
