# Generated by Django 4.2.7 on 2024-04-24 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 16, 33, 59, 974744, tzinfo=datetime.timezone.utc)),
        ),
    ]
