# Generated by Django 4.2.7 on 2024-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="like",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
