# Generated by Django 4.2.7 on 2024-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
