# Generated by Django 4.2.7 on 2024-05-15 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_alter_comment_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="like",
        ),
        migrations.AddField(
            model_name="comment",
            name="liked",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="liked_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="disliked",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="disliked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
