# Generated by Django 4.2.7 on 2024-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_report_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detail',
            field=models.TextField(verbose_name='Additional Details'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('none_educational', 'None Educational'), ('ethnic', 'Ethnic Violence'), ('political', 'Political Content'), ('explicit', 'Explicit Content'), ('spam', 'looks a spam'), ('other', 'other')], max_length=50, verbose_name='Report type'),
        ),
    ]
