# Generated by Django 5.0.4 on 2024-04-24 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 18, 10, 3, 859049, tzinfo=datetime.timezone.utc)),
        ),
    ]
