# Generated by Django 5.0.4 on 2024-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date',), 'verbose_name': 'Post', 'verbose_name_plural': 'posts'},
        ),
    ]
