# Generated by Django 4.2.7 on 2024-05-14 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default=44,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
